name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  pypi:
    strategy:
      matrix:
        python: ['3.10']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build the petl package as source tarball
        run: |
          # python setup.py sdist
          python -m build --sdist --outdir dist/ .

      - name: Publish the package version ${{ github.event.release.tag_name }} to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          print_hash: true
